import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Place the main "MVP Whitepapers" index page first, then token and chain sections
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Token',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'token' }],
    },
    {
      type: 'category',
      label: 'Chain',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'chain' }],
    },
  ],
};

export default sidebars;