import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Minimal sidebar with just the Exchange whitepaper
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Exchange',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'exchange' }],
    },
  ],
};

export default sidebars;