import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Place the main "MVP Exchange Whitepaper" index page first, then the Exchange section
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Exchange',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'exchange' }],
    },
  ],
};

export default sidebars;